### ISSUE TITLE
小bug 配置错别字

### ISSUE THREAD

**Issue by shyx97** [wenqiyun/nest-admin#28]
https://github.com/wenqiyun/nest-admin/blob/dev/servers/src/config/prod.yml

``` yml
mysql:
  host: 'localhost'
  username: 'root'
  password: 'root'
  database: 'kapok'
  port: 3306
  charser: 'utf8mb4'
  # 应该为 charset <------------------------------------------------------------------
  logger: 'advanced-console'
  logging: true
  multipleStatements: true
  dropSchema: false
  synchronize: true
  supportBigNumbers: true
  bigNumberStrings: true
```
